# Generated by Django 3.2.4 on 2021-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pic/raghib.jpg', upload_to='profile_pic'),
        ),
    ]
