# Generated by Django 3.2.4 on 2021-09-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='staus',
            new_name='status',
        ),
    ]
